# Generated by Django 4.2.7 on 2025-01-26 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('micro_10_plazas', 'Micro 10 Plazas (4 a 8 pax)'), ('bus_12_16_plazas', 'Bus 12-16 Plazas (9 a 14 pax)'), ('bus_24_29_plazas', 'Bus 24-29 Plazas (15 a 22 pax)'), ('omnibus_protocolo', 'Ómnibus Protocolo'), ('omnibus_34_plazas', 'Ómnibus 34 Plazas (23-32 Pax)'), ('omnibus_44_plazas', 'Ómnibus 44 Plazas (33-42 Pax)'), ('omnibus_48_plazas', 'Ómnibus 48 Plazas (43-46 Pax)'), ('auto_estandar', 'Auto estándar (1-2 Pax)'), ('auto_lujo', 'Auto Lujo (1-3 Pax)'), ('jeep', 'Jeep (1-4 Pax)'), ('micro_1_5_pax', 'Micro (1-5 Pax)'), ('microbus_6_10_plazas', 'Microbús de 6-10 plazas (6-10 Pax)'), ('minibus_11_16_plazas', 'Minibús hasta 16 plazas (11-16 Pax)'), ('minibus_21_24_plazas', 'Minibús de 21-24 plazas (21-24 Pax)'), ('omnibus_41_49_plazas', 'Ómnibus de 41-49 plazas (41-49 Pax)')], max_length=50, unique=True)),
                ('capacidad_min', models.PositiveIntegerField()),
                ('capacidad_max', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_hacia', to='backoffice.ubicacion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_desde', to='backoffice.ubicacion')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.transportista')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.vehiculo')),
            ],
            options={
                'unique_together': {('transportista', 'origen', 'destino', 'vehiculo')},
            },
        ),
    ]
