# Generated by Django 4.2.7 on 2025-01-31 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_vehiculo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='traslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.traslado'),
        ),
    ]
