# Generated by Django 4.2.7 on 2025-01-31 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_reserva_traslado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='traslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasajeros', to='backoffice.traslado'),
        ),
    ]
