# Generated by Django 4.2.7 on 2025-03-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_pasajero_traslado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('pasaporte', models.CharField(blank=True, max_length=20, null=True)),
                ('carnet_identidad', models.CharField(blank=True, max_length=20, null=True)),
                ('licencia', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidad', models.CharField(blank=True, default='CUB', max_length=50, null=True)),
                ('telefono_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_adicional', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('entre_calle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entre calle')),
                ('y_calle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Y calle')),
                ('apto_reparto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apto/Reparto')),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('es_vip', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('carnet_identidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Carné de Identidad')),
                ('pasaporte_licencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasaporte/Licencia')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_primario', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('reparto', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='ZIP')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
