# Generated by Django 4.2.7 on 2025-03-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_cliente_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='backoffice.cliente'),
            preserve_default=False,
        ),
    ]
