# Generated by Django 4.2.7 on 2025-03-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_contacto_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='calle',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='municipio',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='provincia',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='numero',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='ciudad',
            new_name='apto_reparto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='direccion',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='estado',
            new_name='entre_calle',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='reparto',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apto_reparto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='entre_calle',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='segundo_nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_adicional',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='y_calle',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='piso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='y_calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
