# Generated by Django 4.2.7 on 2025-04-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_rename_calle_cliente_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_remitente', models.CharField(max_length=255)),
                ('nombre_destinatario', models.CharField(max_length=255)),
                ('pasaporte_destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('ci_destinatario', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_destinatario', models.TextField()),
                ('telefono_destinatario', models.CharField(max_length=50)),
                ('email_destinatario', models.EmailField(blank=True, max_length=254, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_envio', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(choices=[('hoteles', 'Hoteles'), ('carros', 'Carros'), ('vuelos', 'Vuelos'), ('remesas', 'Remesas'), ('traslados', 'Traslados'), ('certificado', 'Certificado de Vacaciones'), ('envio', 'Envío')], max_length=20),
        ),
        migrations.CreateModel(
            name='ItemEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hbl', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_aduanal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backoffice.envio')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.envio'),
        ),
    ]
