# Generated by Django 4.2.7 on 2025-04-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_envio_alter_reserva_tipo_itemenvio_reserva_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='documento_remitente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='email_remitente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='telefono_remitente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
