# Generated by Django 4.2.7 on 2025-05-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_envio_documento_remitente_envio_email_remitente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('ci', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('telefono_adicional', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('entre_calle', models.CharField(blank=True, max_length=255, null=True)),
                ('y_calle', models.CharField(blank=True, max_length=255, null=True)),
                ('apto_reparto', models.CharField(blank=True, max_length=255, null=True)),
                ('piso', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('id_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidad', models.CharField(default='CUB', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='envio',
            name='ci_destinatario',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='direccion_destinatario',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='documento_remitente',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='email_destinatario',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='email_remitente',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='nombre_destinatario',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='nombre_remitente',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='pasaporte_destinatario',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='telefono_destinatario',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='telefono_remitente',
        ),
        migrations.AddField(
            model_name='envio',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.destinatario'),
        ),
        migrations.AddField(
            model_name='envio',
            name='remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.remitente'),
        ),
    ]
