# Generated by Django 4.2.7 on 2025-05-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_destinatario_remitente_remove_envio_ci_destinatario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remitente',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='remitente',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='remitente',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='remitente',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='remitente',
            name='segundo_nombre',
        ),
        migrations.AddField(
            model_name='remitente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remitente',
            name='nombre_apellido',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
    ]
