# Generated by Django 4.2.7 on 2025-05-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_remove_remitente_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemenvio',
            name='tipo',
            field=models.CharField(blank=True, choices=[('AE', 'Aéreo'), ('MA', 'Marítimo')], max_length=2, null=True, verbose_name='Tipo de envío'),
        ),
    ]
