# Generated by Django 4.2.7 on 2025-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0013_itemenvio_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=20)),
                ('hotel_code', models.CharField(max_length=50, unique=True)),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_city_code', models.CharField(max_length=20)),
                ('area_id', models.CharField(blank=True, max_length=50, null=True)),
                ('giata_id', models.CharField(blank=True, max_length=50, null=True)),
                ('country_iso_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Hotel Importado',
                'verbose_name_plural': 'Hoteles Importados',
            },
        ),
    ]
