# Generated by Django 4.2.7 on 2025-05-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_hotelimportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hotel_importado',
            field=models.ForeignKey(blank=True, help_text='Aquí guardamos el hotel de Distal Caribe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_distal', to='backoffice.hotelimportado'),
        ),
    ]
