# Generated by Django 4.2.7 on 2025-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0015_reserva_hotel_importado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='agencia',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
