# Generated by Django 4.2.7 on 2025-06-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_reserva_agencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='fee_adultos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fee_ninos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fee_noche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('hoteles', 'Hoteles'), ('carros', 'Carros'), ('vuelos', 'Vuelos'), ('remesas', 'Remesas'), ('traslados', 'Traslados'), ('certificado', 'Certificado de Vacaciones'), ('envio', 'Envío')], default='hoteles', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.proveedor'),
        ),
    ]
