# Generated by Django 4.2.7 on 2025-06-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_destinatario_created_at_remitente_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemenvio',
            name='envio_manejo',
            field=models.CharField(default='Aereo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemenvio',
            name='tipo',
            field=models.CharField(default='aereo', max_length=50),
            preserve_default=False,
        ),
    ]
