# Generated by Django 4.2.7 on 2025-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0019_itemenvio_envio_manejo_alter_itemenvio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemenvio',
            name='envio_manejo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemenvio',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
