# Generated by Django 4.2.7 on 2025-06-11 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0020_alter_itemenvio_envio_manejo_alter_itemenvio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remesa',
            name='direccion_destinatario',
        ),
        migrations.RemoveField(
            model_name='remesa',
            name='documento_remitente',
        ),
        migrations.RemoveField(
            model_name='remesa',
            name='email_remitente',
        ),
        migrations.RemoveField(
            model_name='remesa',
            name='nombre_destinatario',
        ),
        migrations.RemoveField(
            model_name='remesa',
            name='nombre_remitente',
        ),
        migrations.RemoveField(
            model_name='remesa',
            name='telefono_destinatario',
        ),
        migrations.RemoveField(
            model_name='remesa',
            name='telefono_remitente',
        ),
        migrations.AddField(
            model_name='remesa',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.destinatario'),
        ),
        migrations.AddField(
            model_name='remesa',
            name='remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.remitente'),
        ),
        migrations.AddField(
            model_name='tasacambio',
            name='tasa_usd',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Tasa de cambio de USD a USD (útil como referencia o base)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
