# Generated by Django 4.2.7 on 2025-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0021_remove_remesa_direccion_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva_distal',
            field=models.CharField(blank=True, help_text='Código de reserva devuelto por DISTAL (ResID_Type=14).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estatus_api_distal',
            field=models.CharField(blank=True, help_text='Estatus interno de sincronización con la API de Distal: enviado, fallido, confirmado...', max_length=20, null=True),
        ),
    ]
