# Generated by Django 4.2.7 on 2025-06-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0022_reserva_codigo_reserva_distal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacionreserva',
            name='booking_code',
            field=models.CharField(blank=True, help_text='Código completo de booking de la API Distal, ej: HHAVBDMM|BUNDB|SS-BB', max_length=100, null=True),
        ),
    ]
