# Generated by Django 4.2.7 on 2025-01-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fee_traslados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_fee_traslados',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
